[package]
authors = ["Speykious", "BrightShard", "Creative0708"]
categories = ["rust-patterns"]
description = "Blazingly fast memory vulnerabilities, written in 100% safe Rust."
edition = "2021"
keywords = ["cve", "security", "soundness", "safety", "segfault"]
license = "BSD-2-Clause"
name = "cve-rs"
repository = "https://github.com/Speykious/cve-rs"
version = "0.1.0"

[profile.dev]
debug = false
