[package]
name = "cve-rs"
description = "Blazingly fast memory vulnerabilities, written in 100% safe Rust."
authors = ["Speykious", "BrightShard", "Creative0708"]
version = "0.5.0"
edition = "2021"
license-file = "LICENSE"
repository = "https://github.com/Speykious/cve-rs"
categories = ["rust-patterns"]
keywords = ["cve", "security", "soundness", "safety", "segfault"]
rust-version = "1.69.0"

[dependencies]
ureq = { version = "2.9.6", default-features = false, optional = true }
oorandom = { version = "11.1.3", optional = true }

[dev-dependencies]
criterion = "0.5.1"

[profile.dev]
debug = false

[features]
default = []
download-more-ram = ["ureq"]
give-up = ["oorandom"]

[[bench]]
name = "transmute"
harness = false
